LANGUAGES = {
    'English': {
        '[Download Options] All': 'All',
        '[Download Options] Pages:': 'Pages:',
        '[Download Options] Partition': 'Partition',
        '[Download Options] Range:': 'Range:',
        '[MessageBox] About': 'About',
        '[MessageBox] [About Message]': 'Comic FUZ Downloader GUI\n\nThis is an open-source software, hosted on GitHub.',
        '[MessageBox] Error': 'Error',
        '[Proxy] Disabled': 'Disabled',
        '[Proxy] HTTP': 'HTTP',
        '[Proxy] SOCKS5': 'SOCKS5',
        'About': 'About',
        'Browse...': 'Browse...',
        'Cancel': 'Cancel',
        'Canceling...': 'Canceling...',
        'Comic FUZ Manga Downloader GUI': 'Comic FUZ Manga Downloader GUI',
        'Cookies.txt path:': 'Cookies.txt path:',
        'Download begins': 'Download begins',
        'Download Options': 'Download Options',
        'Download Settings': 'Download Settings',
        'Download': 'Download',
        'Failed to download page {page}.': 'Failed to download page {page}.',
        'Failed to fetch manga info. The traceback is listed below.\n{}': 'Failed to fetch manga info. The traceback is listed below.\n{}',
        'Fetch': 'Fetch',
        'Fetching manga info...': 'Fetching manga info...',
        'Help': 'Help',
        'Invalid proxy host name.': 'Invalid proxy host name.',
        'Invalid proxy port.': 'Invalid proxy port.',
        'Langauge': 'Langauge',
        'Manga download finished. {succeed} succeed and {failed} failed.': 'Manga download finished. {succeed} succeed and {failed} failed.',
        'Manga info fetched. Ready to download.': 'Manga info fetched. Ready to download.',
        'Manga Info': 'Manga Info',
        'Manga URL:': 'Manga URL:',
        'Page {page} successfully downloaded.': 'Page {page} successfully downloaded.',
        'Page num:': 'Page num:',
        'Proxy:': 'Proxy:',
        'Save to:': 'Save to:',
        'Select cookies.txt...': 'Select cookies.txt...',
        'Select output directory...': 'Select output directory...',
        'Text files': 'Text files',
        'The cookies.txt does not exist at the given path.': 'The cookies.txt does not exist at the given path.',
        'The download directory is not specified.': 'The download directory is not specified.',
        'The images can not be saved to the specified path.': 'The images can not be saved to the specified path.',
        'The URL in the Manga URL field is invalid.': 'The URL in the Manga URL field is invalid.',
        'Threads num:': 'Threads num:',
        'Title:': 'Title:',
        'Unable to parse Comic FUZ URL. You should specify the URL of the page that reads manga.': 'Unable to parse Comic FUZ URL. You should specify the URL of the page that reads manga.',
        'Welcome to use the downloader.': 'Welcome to use the downloader.',
        'You chose to download part of mangas, but you did not specify correct page ranges.': 'You chose to download part of mangas, but you did not specify correct page ranges.',
    },
    '中文（简体）': {
        '[Download Options] All': '全部下载',
        '[Download Options] Pages:': '页码：',
        '[Download Options] Partition': '部分下载',
        '[Download Options] Range:': '下载范围：',
        '[MessageBox] About': '关于本软件',
        '[MessageBox] [About Message]': 'Comic FUZ Downloader GUI\n\n本软件是开源软件，代码库在 GitHub 上。',
        '[MessageBox] Error': '错误',
        '[Proxy] Disabled': '不用代理',
        '[Proxy] HTTP': 'HTTP',
        '[Proxy] SOCKS5': 'SOCKS5',
        'About': '关于',
        'Browse...': '浏览...',
        'Cancel': '取消',
        'Canceling...': '正在取消……',
        'Comic FUZ Manga Downloader GUI': 'Comic FUZ 漫画下载器 GUI',
        'Cookies.txt path:': 'Cookies.txt 路径：',
        'Download begins': '开始下载',
        'Download Options': '下载选项',
        'Download Settings': '下载设置',
        'Download': '下载',
        'Failed to download page {page}.': '第 {page} 页下载失败。',
        'Failed to fetch manga info. The traceback is listed below.\n{}': '无法获取漫画信息。错误信息如下：{}',
        'Fetch': '获取信息',
        'Fetching manga info...': '正在获取漫画信息……',
        'Help': '帮助',
        'Invalid proxy host name.': '代理设置中的主机名不正确。',
        'Invalid proxy port.': '代理设置中的端口号不正确。',
        'Langauge': '语言(Language)',
        'Manga download finished. {succeed} succeed and {failed} failed.': '漫画下载完毕，{succeed} 张下载成功，{failed} 张下载失败。',
        'Manga info fetched. Ready to download.': '已获取漫画信息，可以下载漫画了。',
        'Manga Info': '漫画信息',
        'Manga URL:': '漫画网址(URL)：',
        'Page {page} successfully downloaded.': '第 {page} 页成功下载。',
        'Page num:': '页码：',
        'Proxy:': '代理：',
        'Save to:': '下载目录：',
        'Select cookies.txt...': '请选择 cookies.txt',
        'Select output directory...': '请选择下载目录……',
        'Text files': '文本文件',
        'The cookies.txt does not exist at the given path.': '您设置的 cookies.txt 路径上的文件不存在。',
        'The download directory is not specified.': '您需要设置下载目录。',
        'The images can not be saved to the specified path.': '图片无法保存到指定位置。',
        'The URL in the Manga URL field is invalid.': '您设置的漫画网址不是正确的网址。',
        'Threads num:': '线程数',
        'Title:': '题目：',
        'Unable to parse Comic FUZ URL. You should specify the URL of the page that reads manga.': '无法解析漫画网址。您需要把阅读漫画时的网页网址填进来。',
        'Welcome to use the downloader.': '欢迎使用本下载器。',
        'You chose to download part of mangas, but you did not specify correct page ranges.': '您选择了“部分下载”，但是您设置的页码不正确。',
    },
}
