__all__ = (
    'DelegatedTask',
    'Parameter',
    'ComicFuzUrlInfo',
    'ComicFuzLicense',
    'ComicFuzFileItem',
    'GuiConfig',
)

from typing import NamedTuple, Tuple, TypedDict, Callable, Mapping, Any


class DelegatedTask(NamedTuple):
    # Function to call
    func: Callable

    # arguments
    args: Tuple = tuple()

    # keyword arguments
    kwargs: Mapping[str, Any] = dict()


class Parameter(NamedTuple):
    # The path to the `cookies.txt` file that can be generated by extensions.
    cookies_txt_path: str

    # URL of the page of Comic FUZ manga reader
    url: str

    # How many thread were used while downloading
    thread_pool_size: int

    # Proxy
    proxy: str


class GuiConfig(TypedDict):
    # Language that was used last time
    language: str

    cookie_txt_path: str

    thread_num: int

    manga_url: str

    save_to_path: str


class ComicFuzUrlInfo(NamedTuple):
    # The original URL
    raw_url: str

    # URL info
    url_scheme: str
    net_loc: str

    # The name of given manga
    manga_name: str

    # The directory name to store manga. In fact this is the escaped `manga_name`
    manga_dir_name: str

    # cid (comic ID) in the URL
    cid: str


class ComicFuzLicense(NamedTuple):
    base_url: str

    # Convert `Policy` in configuration pack into URL-like query string
    policy_query_str: str


class ComicFuzFileItem(NamedTuple):
    index: int
    file_path: str
    file_disk_name: str
    page_no: int
    dummy_pixels: Tuple[int, int]
